local PLUGIN = PLUGIN


for variantI = 1, 4 do

	local pacdata = {	
	[1] = {
	["children"] = {
		[1] = {
			["children"] = {
			},
			["self"] = {
				["ModelIndex"] = 1,
				["DrawOrder"] = 0,
				["UniqueID"] = "ccaa43dea9cf971ccaa767f3021309e21c0832cb0c38c619fd7111ec07ff7edf"..variantI,
				["Hide"] = false,
				["TargetEntityUID"] = "",
				["EditorExpand"] = false,
				["IsDisturbing"] = false,
				["ClassName"] = "bodygroup",
				["Name"] = "",
				["BodyGroupName"] = "body",
			},
		},
		[2] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["ModelIndex"] = variantI,
						["DrawOrder"] = 0,
						["UniqueID"] = "421bc973dfda4114e966ad8315718052cb0ac3dd91b8eb748b4e29e96460efe5"..variantI,
						["Hide"] = false,
						["TargetEntityUID"] = "",
						["EditorExpand"] = false,
						["IsDisturbing"] = false,
						["ClassName"] = "bodygroup",
						["Name"] = "",
						["BodyGroupName"] = "top",
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "e4e770111521491c3d7e528c22e47c53725a6ba7c7b768d324de3fd29e14bd36"..variantI,
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "chest",
				["Angles"] = Angle(0, 0, 0),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Color"] = Vector(1, 1, 1),
				["Position"] = Vector(0, 0, 0),
				["ClassName"] = "model2",
				["Brightness"] = 1,
				["Hide"] = false,
				["NoCulling"] = false,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = true,
				["Size"] = 1,
				["ModelModifiers"] = "",
				["Translucent"] = false,
				["BlendMode"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "models/smalls_civilians/pack2/male/baseballtee/tops.mdl",
			},
		},
		[3] = {
			["children"] = {
			},
			["self"] = {
				["ModelIndex"] = 1,
				["DrawOrder"] = 0,
				["UniqueID"] = "1f3d13f632e3525a54d17a7924287083a5bacee76f7d682f81ce8bd67d3c84c0"..variantI,
				["Hide"] = false,
				["TargetEntityUID"] = "",
				["EditorExpand"] = false,
				["IsDisturbing"] = false,
				["ClassName"] = "bodygroup",
				["Name"] = "",
				["BodyGroupName"] = "hands",
			},
		},
		[4] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["ModelIndex"] = 2,
						["DrawOrder"] = 0,
						["UniqueID"] = "22717f13f381f3fcf32372b71e64ad5357e9bb7eb0c72ebb43a0f1f2c7209eac"..variantI,
						["Hide"] = false,
						["TargetEntityUID"] = "",
						["EditorExpand"] = false,
						["IsDisturbing"] = false,
						["ClassName"] = "bodygroup",
						["Name"] = "",
						["BodyGroupName"] = "arms_baseball",
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "25b77ea978d4d3f6642ef5973a8fbf69723b24181f91560f78933f72b73c0407"..variantI,
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "chest",
				["Angles"] = Angle(0, 0, 0),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Color"] = Vector(1, 1, 1),
				["Position"] = Vector(0, 0, 0),
				["ClassName"] = "model2",
				["Brightness"] = 1,
				["Hide"] = false,
				["NoCulling"] = false,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = true,
				["Size"] = 1,
				["ModelModifiers"] = "",
				["Translucent"] = false,
				["BlendMode"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "models/smalls_civilians/pack2/male/baseballtee/hands.mdl",
			},
		},
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "a375a28d9ab4ba58978c512a75278090a204b1f86a8229e813c3f6c1abc53f65"..variantI,
		["Hide"] = false,
		["TargetEntityUID"] = "",
		["EditorExpand"] = true,
		["OwnerName"] = "self",
		["IsDisturbing"] = false,
		["Name"] = "my outfit",
		["Duplicate"] = false,
		["ClassName"] = "group",
	},
},
}

	PLUGIN:AddClothingPac("baseballtee_"..variantI, pacdata)

end
