local PLUGIN = PLUGIN



local pacdata = {	
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "b120860e3f75b1bb3e906eb2ede1a8161a1d5ee7a8bcfad3a3de33366091920d",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "head",
					["Angles"] = Angle(-2.6913805007935, -68.543075561523, -91.257537841797),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(-58.95703125, -23.102783203125, 1.3885498046875),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/nypd/diverge/coppants_skyblue_shoes.mdl",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "afb4de093309a29d0e88f1f4ee6f0530561c17f53d8d02c024b72ccb7ecf9ed4",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "chest",
					["Angles"] = Angle(0, 0, 0),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(6.103515625e-05, 6.103515625e-05, -55.29296875),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/nypd/diverge/copshirt1_darkblue.mdl",
				},
			},
			[3] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "429ad12491b2985fad42fec3c47bf4e96978c9752c6f33ceb8996c6b430d0dda",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "pelvis",
					["Angles"] = Angle(-84.846466064453, -35.555122375488, -53.903812408447),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(0.33544921875, -44.6318359375, -2.3652954101563),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = true,
					["Size"] = 1,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/nypd/diverge/coppants_darkblue_pant.mdl",
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "3e9c5da0c395f8b97c8196821196956e0d29363e7ed3a3c4535ba1d7476ca9dc",
			["Hide"] = false,
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["IsDisturbing"] = false,
			["Name"] = "my outfit",
			["Duplicate"] = false,
			["ClassName"] = "group",
		},
	},
}



PLUGIN:AddClothingPac("police_outfit", pacdata)

