local PLUGIN = PLUGIN

for variantI = 1, 14 do

	local pacdata = {	
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = (variantI-1),
					["UniqueID"] = "591bfbaf3c6bfbc7f1d5d8c1de0f22a3489dbc0f92a78d3bfb8ccf92ab19a57e"..variantI,
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "skirt",
					["Angles"] = Angle(-1.1838207244873, -89.889175415039, 84.649551391602),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(37.17741394043, 1.52587890625e-05, -3.4811401367188),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/cultist/clothing/male/robbers/r_suit_pants.mdl",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = (variantI-1),
					["UniqueID"] = "825bbb66dd715c10ded745259d0cf762c50cf17f326c06cf6e25f741552fbd29"..variantI,
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "chest",
					["Angles"] = Angle(0, 0, 0),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(-6.866455078125e-05, 0, -52.449264526367),
					["ClassName"] = "model2",
					["Brightness"] = 0.7,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "ties=0;body=0;",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/cultist/clothing/male/robbers/r_closed_suit.mdl",
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "26218bc43f485ccc606cdf36a333991d8b2b5bd0c96509db712ef6cf3e5b0a71"..variantI,
			["Hide"] = false,
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["IsDisturbing"] = false,
			["Name"] = "my outfit",
			["Duplicate"] = false,
			["ClassName"] = "group",
		},
	},


}

	PLUGIN:AddClothingPac("suit_closed_"..variantI, pacdata)

end

for variantI = 1, 14 do

	local pacdata = {	
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = (variantI-1),
					["UniqueID"] = "591bfbasfdsafm230842ge8sfhd8hf8sfusf19a57e"..variantI,
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "skirt",
					["Angles"] = Angle(-1.1838207244873, -89.889175415039, 84.649551391602),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(37.17741394043, 1.52587890625e-05, -3.4811401367188),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/cultist/clothing/male/robbers/r_suit_pants.mdl",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = (variantI-1),
					["UniqueID"] = "825bafsdfa982347rh8fas9e7a97as9dsf7a9d7as7d12312fbd29"..variantI,
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "chest",
					["Angles"] = Angle(0, 0, 0),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(-6.866455078125e-05, 0, -52.449264526367),
					["ClassName"] = "model2",
					["Brightness"] = 0.7,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "ties=0;body=0;",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/cultist/clothing/male/robbers/r_long_coat.mdl",
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "26218bajd1u831u918h2eayda9dhsf9afsd2ef6cf3e5b0a71"..variantI,
			["Hide"] = false,
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["IsDisturbing"] = false,
			["Name"] = "my outfit",
			["Duplicate"] = false,
			["ClassName"] = "group",
		},
	},


}

	PLUGIN:AddClothingPac("suit_longcoat_"..variantI, pacdata)

end

for variantI = 1, 14 do

	local pacdata = {	
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = (variantI-1),
					["UniqueID"] = "59asdfsafai93042fh0s8fd7f712387199a7a98das9d7a98de"..variantI,
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "skirt",
					["Angles"] = Angle(-1.1838207244873, -89.889175415039, 84.649551391602),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(37.17741394043, 1.52587890625e-05, -3.4811401367188),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/cultist/clothing/male/robbers/r_suit_pants.mdl",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = (variantI-1),
					["UniqueID"] = "825asdfsafaf2189340fhe8hfdu8d7f9a781231daasdd29"..variantI,
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "chest",
					["Angles"] = Angle(0, 0, 0),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(-6.866455078125e-05, 0, -52.449264526367),
					["ClassName"] = "model2",
					["Brightness"] = 0.7,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "ties=0;body=0;",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/cultist/clothing/male/robbers/r_open_suit.mdl",
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "26asdfsafafak923i49shjfs98f79821739174981798aa71"..variantI,
			["Hide"] = false,
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["IsDisturbing"] = false,
			["Name"] = "my outfit",
			["Duplicate"] = false,
			["ClassName"] = "group",
		},
	},


}

	PLUGIN:AddClothingPac("suit_open_"..variantI, pacdata)

end


for variantI = 1, 14 do

	local pacdata = {	
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = (variantI-1),
					["UniqueID"] = "5asdfsafsaf9safiu912931823189d9sa8d9a8da89dade"..variantI,
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "skirt",
					["Angles"] = Angle(-1.1838207244873, -89.889175415039, 84.649551391602),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(37.17741394043, 1.52587890625e-05, -3.4811401367188),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/cultist/clothing/male/robbers/r_suit_pants.mdl",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = (variantI-1),
					["UniqueID"] = "825asdfassafkjisf01231831udua8d0saudua8dasddd29"..variantI,
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = false,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "chest",
					["Angles"] = Angle(0, 0, 0),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = true,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(-6.866455078125e-05, 0, -52.449264526367),
					["ClassName"] = "model2",
					["Brightness"] = 0.7,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "ties=0;body=0;",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/b_cansin/setorian/cultist/clothing/male/robbers/r_open_waistcoat.mdl",
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "2adfsafsafkosf19234i192387gsfg97s6f97d69fa71"..variantI,
			["Hide"] = false,
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["IsDisturbing"] = false,
			["Name"] = "my outfit",
			["Duplicate"] = false,
			["ClassName"] = "group",
		},
	},


}

	PLUGIN:AddClothingPac("suit_waistcoat_"..variantI, pacdata)

end