DefaultClientOptions = {
    DrawHUD = true,
    HUDPosX = 25,
    HUDPosY = 25,
    HUDSizeX = 300,
    HUDSizeY = 200,
    CarCamHeight = 3000,
    CamHeight = 5000,
    CarLookAng = 28,
    FOV = 60,
    DrawVOID = true,
    KeepTiltedCamera = false,
    SetHUDColor = Color(255,255,255,200),
    BackgroundOpacity = 0,
    DrawBackgroundBlur = true,
    BackgroundBlurStrength = 40,
    DrawOthers = true,
    DrawOutline = true,
    DrawStamina = false,
    PlayerFadeDistance = 4000,
    DrawOnlyIfSeen = false,
    DefaultChat = true,
    AllowMaximizeMap = false,
    ShowNPC = false,
    blipdefault_player = {mat = "paris/blips/playerblip.png", col = Color(255,255,255,255)},
    blipdefault_npc = {mat = "paris/blips/npcblip.png", col = Color(255,255,255,255)},
    blipdefault_local = {mat = "paris/blips/hudarrow.png", col = Color(255,255,255,255)},
    MaxWantedStars = 5,
}