ITEM.name = "Fishing Rod"
ITEM.description = "A long, tapering rod to which a fishing line is attached, typically on a reel."
ITEM.model = "models/sterling/spook_w_fishingrod.mdl"
ITEM.class = "weapon_fishingrod"
ITEM.weaponCategory = "tools"
ITEM.category = "Tools"
ITEM.flag = "v"
ITEM.width = 2
ITEM.height = 1
ITEM.maxDurability = 100